from pathlib import Path
import re
root=Path(__file__).parent
source=(root.parents[1]/'accueil-native-2026-09-24/elucid-accueil/home.html').read_text(encoding='utf-8')
def section(name):
 text=re.search(r'<section class="'+name+r'\b.*?</section>',source,re.S).group()
 text=text.replace('{{ASSETS}}','../assets').replace('{{SITE}}','https://elucidescape.fr')
 return text
door='''<div class="threshold" aria-hidden="true"><div class="lintel"></div><div class="leaves"><div class="leaf left"><i></i></div><div class="leaf right"><i></i></div></div><div class="mechanism"><svg viewBox="0 0 140 140" fill="none"><circle cx="70" cy="70" r="64"/><circle class="ticks" cx="70" cy="70" r="55"/><path d="M70 30 110 70 70 110 30 70Z"/><path d="M63 70h14M70 63v14"/></svg></div><span class="door-mark">CONTINUEZ ↓</span></div>'''
html='''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Elucid — De porte en porte</title><link rel="stylesheet" href="traversee.css"><script src="traversee.js" defer></script></head><body>
<header class="site-header"><a href="#depart" data-stop="0" aria-label="Elucid Escape, retour au départ"><img src="../assets/logo.svg" width="170" height="65" alt="Elucid Escape"></a><nav aria-label="Navigation"><a href="#rouages" data-stop="1">Les Rouages</a><a href="#cybertrax" data-stop="2">CybertraX</a><a href="#infos">Infos pratiques ↓</a><a class="reserve" href="https://elucidescape.fr/booking/" target="_blank" rel="noopener">Réserver ↗</a></nav></header>
<main>
<div class="journey" id="depart"><div class="viewport">
<section class="world foyer" data-scene="0" data-x=".74" data-y=".53" data-w=".235" data-h=".65" aria-label="L’entrée"><div class="wall"><div class="architecture"><i></i><b></b></div></div><div class="scene-copy"><p class="eyebrow">CHÂLONS-EN-CHAMPAGNE · ESCAPE GAME</p><h1>ELUCID<br>ESCAPE<span>.</span></h1><p class="lead">La suite est<br><em>de l’autre côté.</em></p></div>'''+door+'''</section>
<section class="world rouages" data-scene="1" data-x=".245" data-y=".57" data-w=".20" data-h=".59" id="rouages" aria-label="Les Rouages de l’Apocalypse"><div class="wall"><img class="decor" src="../assets/rouages-1440.webp" width="1440" height="1081" alt="Objets des Rouages de l’Apocalypse"><div class="room-shade"></div></div><div class="scene-copy"><p class="eyebrow">01 — LES ROUAGES DE L’APOCALYPSE</p><h2>Observez.<br><em>Reliez. Élucidez.</em></h2><p>Le Comte et la Comtesse détiennent le remède.<br>À vous de le retrouver.</p><p class="room-meta">2–6 JOUEURS <span>90 MINUTES</span></p></div>'''+door+'''</section>
<section class="world cyber" data-scene="2" data-x=".765" data-y=".48" data-w=".205" data-h=".61" id="cybertrax" aria-label="CybertraX"><div class="wall"><div class="cyber-grid"></div></div><div class="scene-copy"><p class="eyebrow">02 — UN NOUVEL UNIVERS</p><h2>Changez<br><em>de dimension.</em></h2><img class="cyber-sign" src="../assets/cybertrax-1440.webp" width="550" height="367" alt="CybertraX"><p class="room-meta">OUVERTURE PROCHAINE</p></div>'''+door+'''</section>
<section class="world arrival" data-scene="3" aria-label="Préparer votre visite"><div class="wall"><div class="arrival-orbit"></div></div><div class="scene-copy"><p class="eyebrow">LE MONDE PEUT BIEN ATTENDRE.</p><h2>On vous garde<br><em>une place ?</em></h2><p>Tarifs, questions, cadeaux…<br>Tout est juste en dessous.</p><span class="down-arrow" aria-hidden="true">↓</span></div></section>
<div class="route-guide"><span id="route-label">L’ENTRÉE</span><span class="route-line"><i></i></span><span id="route-next">Faites défiler · traversez la porte</span></div>
<div class="scroll-progress" aria-hidden="true"><i></i></div>
</div></div>
<div id="ee-home" class="practical"><div class="practical-intro" id="infos"><p class="eyebrow">L’AVENTURE, CÔTÉ PRATIQUE</p><h2>Préparez votre visite.</h2></div>'''+''.join(section(n) for n in ['ee-pricing','ee-faq','ee-gift','ee-reviews','ee-experience','ee-audience','ee-final'])+'''</div>
</main><footer class="demo-footer"><span>MAQUETTE · TRAVERSÉE AU DÉFILEMENT</span><a href="../hall/">Comparer avec le hall ↗</a><a href="#depart" data-stop="0">Revenir au début ↑</a></footer></body></html>'''
architecture='''<svg class="room-shell" viewBox="0 0 1440 900" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="floor" x2="0" y2="1"><stop stop-color="#212a34"/><stop offset="1" stop-color="#070b10"/></linearGradient><linearGradient id="warm"><stop stop-color="#32271e"/><stop offset="1" stop-color="#15191e"/></linearGradient><linearGradient id="cool"><stop stop-color="#152031"/><stop offset="1" stop-color="#1c2b46"/></linearGradient><radialGradient id="back"><stop stop-color="#303b4b"/><stop offset="1" stop-color="#101720"/></radialGradient></defs><path fill="url(#back)" d="M420 160H1020V680H420Z"/><path fill="url(#warm)" d="M0 0 420 160V680L0 900Z"/><path fill="url(#cool)" d="M1440 0 1020 160V680L1440 900Z"/><path fill="#080d14" d="M0 0H1440L1020 160H420Z"/><path fill="url(#floor)" d="M0 900 420 680H1020L1440 900Z"/><g fill="none" stroke="#abb4c0" stroke-opacity=".12"><path d="M0 0 420 160H1020L1440 0M0 900 420 680H1020L1440 900M420 160V680M1020 160V680"/><path d="M180 0 475 160M1260 0 965 160M0 66 420 205M1440 66 1020 205M0 775 420 630M1440 775 1020 630"/><path d="M250 900 510 680M720 900V680M1190 900 930 680M360 712H1080M265 760H1175M130 830H1310"/></g><g fill="none" stroke="#c4a27a" stroke-opacity=".32"><path d="M0 35 420 180H1020L1440 35M0 873 420 666H1020L1440 873"/></g><path stroke="#f2cd9b" stroke-width="3" opacity=".55" d="M448 170H992"/></svg>'''
hall='''<section class="world room-hall" data-scene="1" data-x=".50" data-y=".50" data-w=".135" data-h=".43" id="salles" aria-label="Le hall des aventures"><div class="wall">'''+architecture+'''<div class="hall-heading"><p class="eyebrow">DEUX PORTES. DEUX UNIVERS.</p><h2>Choisissez votre aventure.</h2></div><div class="side-access left-access"><button class="room-link antique" data-room="rouages" aria-label="Découvrir Les Rouages de l’Apocalypse"><span class="portal-interior"><img src="../assets/rouages-1440.webp" alt=""/><span class="portal-shade"></span><span class="brass-ring"></span></span><span class="room-number">01</span><span class="portal-title">Les Rouages<br><em>de l’Apocalypse</em></span><span class="portal-action">DÉCOUVRIR LA SALLE <b>↗</b></span></button></div><div class="side-access right-access"><button class="room-link laboratory" data-room="cybertrax" aria-label="Découvrir CybertraX"><span class="portal-interior"><span class="lab-lines"></span><img src="../assets/cybertrax-1440.webp" alt=""/><span class="lab-core"></span></span><span class="room-number">02</span><span class="portal-title">CybertraX<small>OUVERTURE PROCHAINE</small></span><span class="portal-action">EXPLORER L’UNIVERS <b>↗</b></span></button></div><div class="floor-light warm-light"></div><div class="floor-light blue-light"></div></div><div class="scene-copy hall-label"><p class="eyebrow">LE HALL DES AVENTURES</p></div>'''+door+'''</section>'''
html=re.sub(r'<section class="world rouages".*?(?=<section class="world arrival")',lambda m:hall,html,flags=re.S)
html=html.replace('data-scene="3"','data-scene="2"').replace('<div class="arrival-orbit"></div>',architecture.replace('id="','id="arrival-').replace('url(#','url(#arrival-'))
html=html.replace('<a href="#rouages" data-stop="1">Les Rouages</a><a href="#cybertrax" data-stop="2">CybertraX</a>','<a href="#salles" data-stop="1">Nos aventures</a>')
html=html.replace('Elucid — De porte en porte','Elucid — Le vestibule').replace('MAQUETTE · TRAVERSÉE AU DÉFILEMENT','MAQUETTE · LE VESTIBULE').replace('../hall/','../traversee/').replace('Comparer avec le hall','L’essai précédent')
dialogs='''<dialog class="room-dialog rouages-dialog" id="dialog-rouages" aria-labelledby="rouages-title"><button class="dialog-close" autofocus>← Revenir au hall <span>×</span></button><div class="dialog-art"><img data-src="../assets/game-v2/room-rouages-v2.jpg" decoding="async" alt="Illustration d’un atelier mécanique aux Rouages de l’Apocalypse"/></div><div class="dialog-copy"><p class="eyebrow">01 — VOTRE AVENTURE</p><h2 id="rouages-title">Les Rouages<br><em>de l’Apocalypse.</em></h2><p>Le Comte et la Comtesse détiennent le remède.<br>À vous de le retrouver.</p><p class="room-meta">2–6 JOUEURS · 90 MINUTES</p><a class="ee-text-link" href="https://elucidescape.fr/booking/">Choisir mon créneau ↗</a></div></dialog><dialog class="room-dialog cyber-dialog" id="dialog-cybertrax" aria-labelledby="cyber-title"><button class="dialog-close" autofocus>← Revenir au hall <span>×</span></button><div class="dialog-art"><img data-src="../assets/game-v2/room-cybertrax-v2.jpg" decoding="async" alt="Illustration d’un laboratoire futuriste CybertraX"/></div><div class="dialog-copy"><p class="eyebrow">02 — UN NOUVEL UNIVERS</p><h2 id="cyber-title">CybertraX.<br><em>Changez de dimension.</em></h2><p>Une autre porte. Une autre aventure.</p><p class="room-meta">OUVERTURE PROCHAINE</p></div></dialog>'''
html=html.replace('</body>',dialogs+'</body>')
from hall_design import apply
html=apply(html)
(root/'index.html').write_text(html,encoding='utf-8')
hall=(root.parent/'hall/hall.css').read_text(encoding='utf-8')
(root/'practical.css').write_text(hall[hall.index('.ee-faq{'):hall.index('.wipe{')],encoding='utf-8')
print('Built entrance, shared hall, two room dialogs and practical sections')
